# SPDX-License-Identifier: FSL-1.1-ALv2
"""Tests for the plan analysis pipeline (task 14.1)."""

import json
from pathlib import Path

import pytest
from src.analysis.plan_analyzer import (
    PlanDocument,
    SchemaStage,
    Severity,
    SyntaxStage,
    ValidationPipeline,
)
from src.analysis.plan_analyzer.models import StageContext

# Path to the real plan sample generated by task 9.5
PLAN_SAMPLE_PATH = Path(__file__).parent.parent.parent.parent / "agent" / "testdata" / "plan-sample.json"


class TestPlanDocument:
    def test_from_json_valid(self):
        data = json.dumps(
            {
                "format_version": "1.2",
                "terraform_version": "1.12.5",
                "resource_changes": [{"address": "null_resource.test", "change": {"actions": ["create"]}}],
            }
        )
        doc = PlanDocument.from_json(data)
        assert doc.format_version == "1.2"
        assert doc.terraform_version == "1.12.5"
        assert len(doc.resource_changes) == 1

    def test_from_json_invalid(self):
        with pytest.raises(ValueError, match="Invalid plan JSON"):
            PlanDocument.from_json("not json")

    def test_from_json_not_object(self):
        with pytest.raises(ValueError, match="must be an object"):
            PlanDocument.from_json("[1, 2, 3]")

    def test_from_json_real_sample(self):
        """Test using the real plan-sample.json from task 9.5."""
        if not PLAN_SAMPLE_PATH.exists():
            pytest.fail(
                "agent/testdata/plan-sample.json is committed and is criterion 13's "
                "only fixture; a missing file must fail, not skip"
            )
        data = PLAN_SAMPLE_PATH.read_text(encoding="utf-8")
        doc = PlanDocument.from_json(data)
        assert doc.format_version == "1.2"
        assert doc.terraform_version == "1.12.5"
        assert len(doc.resource_changes) == 1
        assert doc.resource_changes[0]["address"] == "null_resource.test"


class TestSyntaxStage:
    async def test_valid_plan(self):
        doc = PlanDocument.from_json(
            json.dumps(
                {
                    "format_version": "1.2",
                    "terraform_version": "1.12.5",
                    "resource_changes": [],
                }
            )
        )
        stage = SyntaxStage()
        findings = await stage.run(doc, StageContext())
        assert len(findings) == 0

    async def test_empty_plan(self):
        doc = PlanDocument(raw={}, format_version="", terraform_version="")
        stage = SyntaxStage()
        findings = await stage.run(doc, StageContext())
        assert any(f.severity == Severity.FATAL for f in findings)
        assert any(f.code == "EMPTY_PLAN" for f in findings)

    async def test_missing_format_version(self):
        doc = PlanDocument.from_json(
            json.dumps(
                {
                    "terraform_version": "1.12.5",
                    "resource_changes": [],
                }
            )
        )
        stage = SyntaxStage()
        findings = await stage.run(doc, StageContext())
        assert any(f.code == "MISSING_FORMAT_VERSION" for f in findings)


class TestSchemaStage:
    async def test_valid_resource_change(self):
        doc = PlanDocument.from_json(
            json.dumps(
                {
                    "format_version": "1.2",
                    "terraform_version": "1.12.5",
                    "resource_changes": [{"address": "null_resource.test", "change": {"actions": ["create"]}}],
                }
            )
        )
        stage = SchemaStage()
        findings = await stage.run(doc, StageContext())
        assert len(findings) == 0

    async def test_missing_address(self):
        doc = PlanDocument.from_json(
            json.dumps(
                {
                    "format_version": "1.2",
                    "resource_changes": [{"change": {"actions": ["create"]}}],
                }
            )
        )
        stage = SchemaStage()
        findings = await stage.run(doc, StageContext())
        assert any(f.code == "MISSING_ADDRESS" for f in findings)

    async def test_missing_change(self):
        doc = PlanDocument.from_json(
            json.dumps(
                {
                    "format_version": "1.2",
                    "resource_changes": [{"address": "foo.bar"}],
                }
            )
        )
        stage = SchemaStage()
        findings = await stage.run(doc, StageContext())
        assert any(f.code == "MISSING_CHANGE" for f in findings)


class TestValidationPipeline:
    async def test_stages_run_in_order(self):
        pipeline = ValidationPipeline([SyntaxStage(), SchemaStage()])
        doc = PlanDocument.from_json(
            json.dumps(
                {
                    "format_version": "1.2",
                    "terraform_version": "1.12.5",
                    "resource_changes": [{"address": "a.b", "change": {"actions": ["create"]}}],
                }
            )
        )
        result = await pipeline.run(doc)
        assert result.stages_run == ("syntax", "schema")
        assert not result.fatal

    async def test_fatal_short_circuits(self):
        # Empty plan triggers FATAL in syntax, so schema should NOT run
        pipeline = ValidationPipeline([SyntaxStage(), SchemaStage()])
        doc = PlanDocument(raw={}, format_version="", terraform_version="")
        result = await pipeline.run(doc)
        assert result.fatal
        assert result.stages_run == ("syntax",)  # schema not reached
        assert any(f.code == "EMPTY_PLAN" for f in result.findings)

    async def test_non_fatal_accumulates(self):
        doc = PlanDocument.from_json(
            json.dumps(
                {
                    "format_version": "1.2",
                    "resource_changes": [{"address": "a.b"}],  # missing change field
                }
            )
        )
        pipeline = ValidationPipeline([SyntaxStage(), SchemaStage()])
        result = await pipeline.run(doc)
        assert not result.fatal
        assert result.stages_run == ("syntax", "schema")
        # Should have findings from both stages
        assert any(f.code == "MISSING_TERRAFORM_VERSION" for f in result.findings)
        assert any(f.code == "MISSING_CHANGE" for f in result.findings)

    async def test_real_sample(self):
        """Pipeline over the real plan-sample.json."""
        if not PLAN_SAMPLE_PATH.exists():
            pytest.fail(
                "agent/testdata/plan-sample.json is committed and is criterion 13's "
                "only fixture; a missing file must fail, not skip"
            )
        data = PLAN_SAMPLE_PATH.read_text(encoding="utf-8")
        doc = PlanDocument.from_json(data)
        pipeline = ValidationPipeline()
        result = await pipeline.run(doc)
        assert not result.fatal
        assert result.stages_run == ("syntax", "schema")
        # Real sample should have no errors
        errors = [f for f in result.findings if f.severity in (Severity.ERROR, Severity.FATAL)]
        assert len(errors) == 0
