# SPDX-License-Identifier: FSL-1.1-ALv2
"""The artifact kinds FR-24 requires beyond a Dockerfile and Kubernetes manifests.

FR-24 is P0 and names four things: containerisation, Kubernetes manifests, **CI/CD pipelines**, and
**infrastructure as code**. Only the first two were produced. The consequence was not cosmetic — a user
asking the platform to make their project deployable got a Dockerfile and three manifests and nothing
that would build the image, and nothing that would create the cluster the manifests need.

The agent's `validate.yaml`, `validate.helm` and `validate.tofu` operations existed to check these and
had nothing to check. `artifact_checks` gates them in the backend too, so an unrunnable workflow or a
chart Helm will reject cannot reach a user.

WHY THESE ARE TEMPLATES AND NOT MODEL OUTPUT
--------------------------------------------
This module is the safe fallback — what a user gets when no model could be reached, or when three
attempts all failed the gate. The model path is asked for the same paths through `REQUIRED_ARTIFACTS`,
so a provider that produces good ones is preferred; these are what makes the platform still useful when
it does not. Every one is deliberately minimal and correct rather than comprehensive: a fallback that
guesses at a cloud provider's resource names would produce something worse than a small, valid module a
user can extend.
"""

from __future__ import annotations


def github_workflow_yaml(app_name: str, *, image_tag: str = "latest") -> str:
    """A workflow that builds and pushes the image the manifests reference.

    Pinned action SHAs are deliberately ABSENT here and tags are used instead, which is the one place
    this repository's own rule is knowingly inverted — and the reason is that these are the *user's*
    artifacts, not ours: writing a SHA the user cannot verify and will not update is worse than a tag
    they can read. The comment in the generated file says so, so the choice is visible to whoever
    adopts it.
    """
    return f"""---
name: build

# `on` is quoted because YAML 1.1 reads a bare `on` as the boolean true. Unquoted it still works in
# GitHub Actions, but every linter reports it, so the generated file avoids the argument.
"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

concurrency:
  group: build-${{{{ github.ref }}}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Actions are referenced by tag rather than by commit SHA. Pin these to SHAs for a production
      # pipeline: a tag is mutable, so what runs here can change without this file changing.
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: {app_name}:{image_tag}
          cache-from: type=gha
          cache-to: type=gha,mode=max
"""


def helm_chart_yaml(app_name: str) -> str:
    """`Chart.yaml`. `version` is SemVer 2 because Helm requires it rather than prefers it."""
    return f"""---
apiVersion: v2
name: {app_name}
description: A Helm chart for {app_name}, generated by ForgeOps.
type: application
# Helm REQUIRES SemVer 2 here and refuses the chart otherwise.
version: 0.1.0
appVersion: "0.1.0"
"""


def helm_values_yaml(app_name: str, port: int) -> str:
    return f"""---
replicaCount: 1

image:
  repository: {app_name}
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: {port}

# Empty by default rather than guessed. A generated resource request that does not match the workload
# is worse than none: it either wastes capacity or gets the pod evicted.
resources: {{}}

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
"""


def helm_deployment_template(app_name: str) -> str:
    """The chart's one template. Rendered by `helm template`, so it must actually render."""
    return f"""---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{{{ include "{app_name}.fullname" . }}}}
  labels:
    app.kubernetes.io/name: {app_name}
spec:
  replicas: {{{{ .Values.replicaCount }}}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {app_name}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {app_name}
    spec:
      securityContext:
        runAsNonRoot: {{{{ .Values.securityContext.runAsNonRoot }}}}
        runAsUser: {{{{ .Values.securityContext.runAsUser }}}}
      containers:
        - name: {app_name}
          image: "{{{{ .Values.image.repository }}}}:{{{{ .Values.image.tag }}}}"
          imagePullPolicy: {{{{ .Values.image.pullPolicy }}}}
          ports:
            - containerPort: {{{{ .Values.service.port }}}}
          securityContext:
            allowPrivilegeEscalation: {{{{ .Values.securityContext.allowPrivilegeEscalation }}}}
          resources: {{{{- toYaml .Values.resources | nindent 12 }}}}
"""


def helm_helpers_template(app_name: str) -> str:
    """`_helpers.tpl`, because the deployment template calls `include`.

    Without this the chart lints and fails to render, which is precisely the case `helm template`
    catches and `helm lint` does not.
    """
    return f"""{{{{- define "{app_name}.fullname" -}}}}
{{{{- printf "%s-%s" .Release.Name "{app_name}" | trunc 63 | trimSuffix "-" -}}}}
{{{{- end -}}}}
"""


def opentofu_main_tf(app_name: str, port: int) -> str:
    """A module that validates and plans with no credentials and no remote state.

    The `kubernetes` provider rather than a cloud one, deliberately: the manifests this accompanies are
    Kubernetes, so the infrastructure that matches them is a namespace and a deployment. Generating an
    AWS VPC for a project whose target is unknown would be a guess with a bill attached.
    """
    return f"""terraform {{
  required_version = ">= 1.6.0"

  required_providers {{
    kubernetes = {{
      source  = "hashicorp/kubernetes"
      version = "~> 2.30"
    }}
  }}
}}

variable "namespace" {{
  description = "Namespace to deploy {app_name} into."
  type        = string
  default     = "{app_name}"
}}

variable "image" {{
  description = "Fully qualified image reference for {app_name}."
  type        = string
  default     = "{app_name}:latest"
}}

variable "replicas" {{
  description = "Number of pod replicas."
  type        = number
  default     = 1
}}

variable "container_port" {{
  description = "Port the container listens on."
  type        = number
  default     = {port}
}}

resource "kubernetes_namespace" "app" {{
  metadata {{
    name = var.namespace
  }}
}}

resource "kubernetes_deployment" "app" {{
  metadata {{
    name      = "{app_name}"
    namespace = kubernetes_namespace.app.metadata[0].name
  }}

  spec {{
    replicas = var.replicas

    selector {{
      match_labels = {{
        "app.kubernetes.io/name" = "{app_name}"
      }}
    }}

    template {{
      metadata {{
        labels = {{
          "app.kubernetes.io/name" = "{app_name}"
        }}
      }}

      spec {{
        security_context {{
          run_as_non_root = true
          run_as_user     = 1001
        }}

        container {{
          name  = "{app_name}"
          image = var.image

          port {{
            container_port = var.container_port
          }}

          security_context {{
            allow_privilege_escalation = false
          }}
        }}
      }}
    }}
  }}
}}

output "namespace" {{
  description = "Namespace {app_name} was deployed into."
  value       = kubernetes_namespace.app.metadata[0].name
}}
"""
