<#
.SYNOPSIS
  Install the cheap half of the pre-commit gate as a real git hook.

.DESCRIPTION
  `.pre-commit-config.yaml` declares `check-added-shapes`, but this repository does not run the
  pre-commit framework from `.git/hooks` -- it runs it explicitly through `scripts/leaf-gate.ps1`
  (D-76), and `git commit` itself fires no hook at all. That is enough for a session that runs the
  gate, and not enough for the guarantee finding 64 asks for, which is that a credential shape
  cannot enter a commit AT ALL.

  So the one check that costs seconds is installed as `.git/hooks/pre-commit` directly. The full
  hook set is deliberately NOT installed here: it pulls a Gitleaks container and reformats files
  mid-commit, which is why this repository invokes it from a script in the first place.

  Interaction with the framework, stated so nobody has to discover it: if somebody later runs
  `pre-commit install`, it moves this file to `pre-commit.legacy` and its own generated hook keeps
  calling it. Nothing is silently lost. `core.hooksPath` is deliberately not used, because that
  WOULD make a later `pre-commit install` a no-op.

  Re-runnable. Refuses to overwrite a hook it did not write.

.EXAMPLE
  powershell -NoProfile -File scripts\install-git-hooks.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$HookPath = Join-Path $RepoRoot '.git\hooks\pre-commit'
$Marker = '# generated by scripts/install-git-hooks.ps1'

# `sh` is what git invokes a hook with on every platform, and Git for Windows ships one. The
# interpreter is resolved at run time rather than baked in, so the same hook works from a Linux
# clone whose virtualenv lives in `bin/` instead of `Scripts/`.
$Body = @'
#!/bin/sh
# generated by scripts/install-git-hooks.ps1 -- do not edit; re-run that script instead.
#
# FO-SEC001 at commit time (finding 64). The full pre-commit set is run through
# scripts/leaf-gate.ps1; only this check is cheap enough to pay on every commit.
set -e
root="$(git rev-parse --show-toplevel)"
for candidate in \
    "$root/backend/.venv/Scripts/python.exe" \
    "$root/backend/.venv/bin/python" \
    "$(command -v python3 || true)" \
    "$(command -v python || true)"
do
    if [ -n "$candidate" ] && [ -x "$candidate" ]; then
        exec "$candidate" "$root/scripts/check-added-shapes.py"
    fi
done
echo "pre-commit: no python found to run scripts/check-added-shapes.py" >&2
echo "The shape gate could not run. That is a block, not a pass: FO-SEC001 is not optional." >&2
exit 1
'@ -replace "`r`n", "`n"

if (Test-Path $HookPath) {
    $existing = [System.IO.File]::ReadAllText($HookPath)
    if ($existing -notlike "*$Marker*") {
        Write-Error "$HookPath exists and was not written by this script; refusing to overwrite it."
        exit 1
    }
}

[System.IO.File]::WriteAllText($HookPath, $Body, (New-Object System.Text.UTF8Encoding $false))
Write-Host "installed $HookPath"
Write-Host 'It runs scripts/check-added-shapes.py over the staged diff and blocks on any hit.'
