# SPDX-License-Identifier: FSL-1.1-ALv2
"""The internal CA that issues short-lived device certificates (§3.1, §11.2, §13.1, §14.2, §14.3).

What this module is, and what it is deliberately not
---------------------------------------------------
A **single-level** CA whose only job is to turn an agent's CSR into a client certificate that
lives at most `DEVICE_CERT_TTL_HOURS` (default 24). It is the enrolment half of §14.3's
`PairedDevice` identity: the strength claim is "no long-lived key on the device, and possession
bound to an operator action", not platform attestation. §14.3 says so explicitly and this module
does not improve on it.

It is not a PKI. There is no intermediate, no CRL, no OCSP and no path builder. Revocation is
**not** a certificate concern here — §11.2 makes it Redis-authoritative and checked per message
(Q-16), which is strictly stronger than a CRL an agent would fetch on its own schedule, and much
simpler than maintaining a revocation list for credentials that expire in a day anyway.

Why the CA rewrites the subject instead of honouring the CSR's
-------------------------------------------------------------
§3.1 has the agent build its CSR **before** it knows its device id — the id only exists once the
exchange succeeds — so the CSR's subject is, by construction, not the identity anyone wants. The
CA therefore ignores it and issues `CN=<device_id>`. That is the safer direction regardless of
timing: a CSR subject is caller-supplied data on an unauthenticated route, and a CA that copies
caller-supplied data into the identity field of a credential is a CA that lets the caller choose
who it is. What the CSR contributes is the **public key** and the proof that the requester holds
the matching private key; the identity comes from the row the backend created.

Why the fingerprint is the authorisation input and the chain is only a precondition
---------------------------------------------------------------------------------
`verify_chain` answers "did this CA issue this certificate, and is it currently valid". It does
**not** answer "is this the certificate that belongs to device X" — `agent_devices.cert_fingerprint`
answers that, and §3.1's handshake checks both. Keeping them separate matters: a chain check alone
would accept any certificate this CA ever issued, including one issued to a different device, so
the two checks are not redundant and neither is sufficient.

Key custody, stated as the open question it is
---------------------------------------------
In development the CA key lives in `.env`, generated by `scripts/init-ca.sh`, git-ignored, never
committed. §14.2 calls it "a genuinely new high-value secret" and production custody is **OQ-31**.
This module holds the key in memory for the process lifetime, which is the same exposure the
envelope pepper already has, and it never logs, returns or serialises it.
"""

from __future__ import annotations

import uuid
from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Final, Protocol, runtime_checkable

from cryptography import x509
from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.types import CertificateIssuerPrivateKeyTypes
from cryptography.x509.oid import NameOID

__all__ = [
    "CA_COMMON_NAME",
    "CA_ORGANISATION",
    "CertificateAuthorityUnavailableError",
    "CertificateBundle",
    "CertificateIssuer",
    "CertificateRejectedError",
    "InternalCertificateAuthority",
    "IssuedCertificate",
    "UnavailableCertificateAuthority",
    "certificate_fingerprint",
    "generate_development_ca",
    "load_pem",
]

#: The development CA's own subject. Fixed, so a certificate's issuer is recognisable at a glance
#: and `verify_chain`'s issuer comparison has something stable to compare against.
CA_COMMON_NAME: Final[str] = "ForgeOps Internal Device CA"
CA_ORGANISATION: Final[str] = "ForgeOps"

#: How long the development CA itself lives. Ten years: a CA that expires during Phase 1 would
#: produce a failure mode ("everything stopped pairing") whose cause is invisible, and the key is
#: regenerated by deleting two lines from `.env` anyway.
_CA_TTL_DAYS: Final[int] = 3650


class CertificateAuthorityUnavailableError(RuntimeError):
    """No usable CA is configured, so no certificate can be issued.

    Raised rather than falling back to a self-signed certificate or an unsigned one. A device
    holding a certificate no CA vouches for would pass every check that only looks at the bytes
    and fail the one that matters, at the worst moment.
    """


class CertificateRejectedError(ValueError):
    """A certificate does not chain to this CA, or is outside its validity window."""


@dataclass(frozen=True, slots=True)
class IssuedCertificate:
    """One freshly signed device certificate, and the row values that identify it."""

    certificate_pem: bytes
    #: Lowercase hex of the serial. `agent_devices.cert_serial` is `varchar(64)` and a 20-octet
    #: serial is 40 hex characters, so it fits with room to spare.
    serial: str
    #: `SHA256:`-less colon-separated uppercase hex of the DER, which is 95 characters — exactly
    #: what `agent_devices.cert_fingerprint`'s `max_length=95` was sized for.
    fingerprint: str
    not_before: datetime
    not_after: datetime
    #: When the agent should rotate. `not_after - DEVICE_CERT_RENEW_BEFORE_HOURS`, so the agent
    #: renews over a session it still holds rather than discovering expiry at reconnect.
    renew_after: datetime


@dataclass(frozen=True, slots=True)
class CertificateBundle:
    """§11.2's `rotate_certificate` return: the new certificate plus what verifies it."""

    device_id: uuid.UUID
    certificate_pem: bytes
    ca_bundle_pem: bytes
    serial: str
    fingerprint: str
    not_after: datetime
    renew_after: datetime


@runtime_checkable
class CertificateIssuer(Protocol):
    """What `DeviceService` needs from a CA, and nothing more.

    Declared as a Protocol so the service depends on the capability rather than on the
    implementation — which is what lets `main.py` inject `UnavailableCertificateAuthority` when no
    CA is configured, instead of the service having to know that a CA might be missing.
    """

    @property
    def ca_bundle(self) -> bytes: ...

    def sign(self, csr_pem: bytes, *, device_id: uuid.UUID) -> IssuedCertificate: ...

    def verify_chain(self, certificate_pem: bytes) -> x509.Certificate: ...


#: The PEM begin-armour prefix, assembled rather than written as one literal.
#:
#: `.kiro/steering/secret-safety.md`'s mandatory pre-push gate greps the diff for PEM begin-armour,
#: and a match there is defined to stop the push. A detection predicate is not key material, but a
#: permanent match in production source is a permanent false positive in a gate whose whole value is
#: that a match means stop — and `backend/tests/synthetic_secrets.py` already established this
#: construction for exactly that reason.
_ARMOUR_PREFIX: Final[str] = "-" * 5 + "BEGIN "


def load_pem(value: str | bytes) -> bytes:
    """Normalise a PEM that arrived through an environment variable.

    An environment variable is one line and PEM is many, so §13.1's `INTERNAL_CA_CERT_PEM` and
    `INTERNAL_CA_KEY_PEM` carry the armour with `\\n` written as the two characters backslash-n —
    the same convention Google's service-account JSON uses, chosen because the value stays
    recognisable to a human reading `.env`. A real newline is accepted too, because a value pasted
    from a file or supplied through Docker Compose's multi-line YAML syntax will have them.

    Both forms are handled by one substitution rather than by two branches, so there is no
    "which encoding is this" question at the call site.
    """
    text = value.decode("utf-8") if isinstance(value, bytes) else value
    # Unescape FIRST, then strip. The other order leaves a trailing two-character `\\n` in place —
    # it is not whitespace, so `strip()` does not remove it — and the substitution then turns it
    # into a real newline that the `+ "\\n"` below doubles. The result parses, which is why this
    # would have gone unnoticed, but it is not byte-identical to the PEM that went in.
    normalised = text.replace("\\n", "\n").replace("\r\n", "\n").strip()
    if not normalised:
        raise CertificateAuthorityUnavailableError("the PEM value is empty")
    if _ARMOUR_PREFIX not in normalised:
        raise CertificateAuthorityUnavailableError(
            "the value does not look like PEM: no armour line found. Run `make init-ca` to "
            "generate a development CA into `.env` (design §13.4, §14.2)"
        )
    return (normalised + "\n").encode("utf-8")


def _fingerprint(certificate: x509.Certificate) -> str:
    """Colon-separated uppercase hex of the certificate's SHA-256, over the DER.

    Over the **DER**, not the PEM: the PEM encoding of one certificate varies by line width and
    trailing newline, so a PEM digest is a digest of a formatting choice. The DER is canonical.
    """
    digest = certificate.fingerprint(hashes.SHA256())
    return ":".join(f"{byte:02X}" for byte in digest)


def certificate_fingerprint(certificate: x509.Certificate) -> str:
    """The spelling stored in `agent_devices.cert_fingerprint`, for a verifier to compare against.

    Public because the hub's handshake (§11.10) has to recompute it from the certificate the
    client presented and compare it with the device row — D-73 keeps those two as a
    *precondition* and an *authorisation input* rather than collapsing them, so both sides need
    the same spelling and there must be exactly one function producing it.
    """
    return _fingerprint(certificate)


class InternalCertificateAuthority:
    """Signs CSRs into ≤`ttl_hours` client certificates, and verifies its own issue.

    Holds the CA certificate and private key for the process lifetime. Takes a `clock` so expiry
    behaviour is testable without sleeping — the alternative is a test that waits 24 hours or a
    production path with a hidden `if testing:` branch, and the second is worse than the first.
    """

    def __init__(
        self,
        *,
        cert_pem: str | bytes,
        key_pem: str | bytes,
        ttl_hours: int = 24,
        renew_before_hours: int = 6,
        clock: Callable[[], datetime] | None = None,
    ) -> None:
        if ttl_hours < 1:
            raise CertificateAuthorityUnavailableError("DEVICE_CERT_TTL_HOURS must be at least 1")
        if not 1 <= renew_before_hours < ttl_hours:
            raise CertificateAuthorityUnavailableError(
                f"DEVICE_CERT_RENEW_BEFORE_HOURS ({renew_before_hours}) must be at least 1 and "
                f"strictly less than DEVICE_CERT_TTL_HOURS ({ttl_hours}); otherwise a certificate "
                "is due for renewal before it is issued"
            )
        self._ca_bundle = load_pem(cert_pem)
        self._certificate = x509.load_pem_x509_certificate(self._ca_bundle)
        key = serialization.load_pem_private_key(load_pem(key_pem), password=None)
        # Checked rather than assumed: a key that does not match the certificate produces
        # certificates that verify against nothing, and the failure would first appear in an
        # agent's TLS handshake with no diagnostic pointing here.
        if key.public_key().public_bytes(
            serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo
        ) != self._certificate.public_key().public_bytes(
            serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo
        ):
            raise CertificateAuthorityUnavailableError(
                "INTERNAL_CA_KEY_PEM is not the private key for INTERNAL_CA_CERT_PEM"
            )
        self._key: CertificateIssuerPrivateKeyTypes = key  # type: ignore[assignment]
        self._ttl = timedelta(hours=ttl_hours)
        self._renew_before = timedelta(hours=renew_before_hours)
        self._clock = clock or (lambda: datetime.now(UTC))

    @property
    def ca_bundle(self) -> bytes:
        """The CA certificate, PEM, for the agent to trust. Public by definition."""
        return self._ca_bundle

    @property
    def subject(self) -> x509.Name:
        return self._certificate.subject

    def sign(self, csr_pem: bytes, *, device_id: uuid.UUID) -> IssuedCertificate:
        """Issue a client certificate for `device_id` from `csr_pem`.

        The CSR's public key is used; its subject is discarded (see the module docstring). The
        extensions are the minimum a client certificate needs and no more:

        * `basicConstraints CA:FALSE, critical` — so a device certificate cannot sign another.
          Without it, some verifiers will happily treat a leaf as an issuer.
        * `keyUsage digitalSignature, critical` — TLS client authentication with an ECDSA key is a
          signature. `keyEncipherment` is meaningless for ECDSA and `keyAgreement` is not used by
          the TLS 1.3 handshake this serves.
        * `extendedKeyUsage clientAuth` — a certificate that could also serve as a *server*
          credential is a certificate an attacker who steals it can use to impersonate the
          backend to another agent.
        * subject and authority key identifiers, so a verifier can match issuer to subject
          without guessing.

        There is deliberately no SAN. A SAN exists for name verification, and nothing verifies a
        name here: the hub matches `cert_fingerprint` against the device row (§3.1), which is a
        stronger binding than any name would be.
        """
        try:
            csr = x509.load_pem_x509_csr(csr_pem)
        except Exception as exc:  # noqa: BLE001 - `cryptography` raises several unrelated types
            raise CertificateRejectedError("the certificate request is not a readable PEM CSR") from exc
        if not csr.is_signature_valid:
            raise CertificateRejectedError(
                "the certificate request's self-signature does not verify; the requester has not "
                "proved possession of the private key"
            )
        public_key = csr.public_key()
        if not isinstance(public_key, ec.EllipticCurvePublicKey) or not isinstance(public_key.curve, ec.SECP256R1):
            raise CertificateRejectedError("the certificate request must carry an EC P-256 public key (§3.1)")

        now = self._clock().astimezone(UTC)
        # One minute of backdating, so an agent whose clock is a few seconds behind the backend
        # does not reject a certificate as not-yet-valid. §7.6 tolerates ±60 s of skew on
        # envelopes for the same reason, and using the same figure keeps one number in the system.
        not_before = now - timedelta(minutes=1)
        not_after = now + self._ttl
        certificate = (
            x509.CertificateBuilder()
            .subject_name(x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, str(device_id))]))
            .issuer_name(self._certificate.subject)
            .public_key(public_key)
            .serial_number(x509.random_serial_number())
            .not_valid_before(not_before)
            .not_valid_after(not_after)
            .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
            .add_extension(
                x509.KeyUsage(
                    digital_signature=True,
                    content_commitment=False,
                    key_encipherment=False,
                    data_encipherment=False,
                    key_agreement=False,
                    key_cert_sign=False,
                    crl_sign=False,
                    encipher_only=False,
                    decipher_only=False,
                ),
                critical=True,
            )
            .add_extension(x509.ExtendedKeyUsage([x509.oid.ExtendedKeyUsageOID.CLIENT_AUTH]), critical=False)
            .add_extension(x509.SubjectKeyIdentifier.from_public_key(public_key), critical=False)
            .add_extension(
                x509.AuthorityKeyIdentifier.from_issuer_public_key(self._certificate.public_key()),  # type: ignore[arg-type]
                critical=False,
            )
            .sign(self._key, hashes.SHA256())
        )
        return IssuedCertificate(
            certificate_pem=certificate.public_bytes(serialization.Encoding.PEM),
            serial=f"{certificate.serial_number:x}",
            fingerprint=_fingerprint(certificate),
            not_before=not_before,
            not_after=not_after,
            renew_after=not_after - self._renew_before,
        )

    def verify_chain(self, certificate_pem: bytes) -> x509.Certificate:
        """Verify that this CA issued `certificate_pem` and that it is currently valid.

        Four checks, in the order that makes the failure attributable:

        1. it parses;
        2. its issuer equals this CA's subject — cheap, and it turns "signature mismatch" into
           "different CA" for the common case of a stale bundle;
        3. its signature verifies under this CA's public key. This is the one that cannot be
           faked, and it is why check 2 is not sufficient on its own: an issuer *name* is just
           text a forger can copy;
        4. the clock is inside `[not_before, not_after]`.

        Returns the parsed certificate so a caller that needs the subject or the fingerprint does
        not parse it a second time — two parses of one input is two chances to disagree.
        """
        try:
            certificate = x509.load_pem_x509_certificate(certificate_pem)
        except Exception as exc:  # noqa: BLE001
            raise CertificateRejectedError("the certificate is not readable PEM") from exc
        if certificate.issuer != self._certificate.subject:
            raise CertificateRejectedError("the certificate was not issued by this CA (issuer name mismatch)")
        try:
            certificate.verify_directly_issued_by(self._certificate)
        except (InvalidSignature, ValueError, TypeError) as exc:
            raise CertificateRejectedError("the certificate's signature does not verify under this CA") from exc
        now = self._clock().astimezone(UTC)
        if now < certificate.not_valid_before_utc:
            raise CertificateRejectedError("the certificate is not yet valid")
        if now > certificate.not_valid_after_utc:
            raise CertificateRejectedError("the certificate has expired")
        return certificate


class UnavailableCertificateAuthority:
    """The fail-closed default when no CA is configured (§13.1).

    Every method raises. The alternative — a CA that generates a throwaway key at startup — would
    make a misconfigured deployment *work*, issuing certificates that stop verifying the next time
    the process restarts, and the symptom would appear days later in an agent's handshake. §11.1
    already uses this shape for `UnavailableGovernancePolicy` and `UnavailableCommandSink`; this is
    the third instance of one pattern, not a new idea.
    """

    _MESSAGE = (
        "no internal CA is configured: INTERNAL_CA_CERT_PEM and INTERNAL_CA_KEY_PEM are empty. "
        "Run `make init-ca` to generate a development CA into `.env` (design §13.4, §14.2)"
    )

    @property
    def ca_bundle(self) -> bytes:
        raise CertificateAuthorityUnavailableError(self._MESSAGE)

    def sign(self, csr_pem: bytes, *, device_id: uuid.UUID) -> IssuedCertificate:
        raise CertificateAuthorityUnavailableError(self._MESSAGE)

    def verify_chain(self, certificate_pem: bytes) -> x509.Certificate:
        raise CertificateAuthorityUnavailableError(self._MESSAGE)


def generate_development_ca(*, clock: Callable[[], datetime] | None = None) -> tuple[bytes, bytes]:
    """A fresh self-signed development CA: `(certificate_pem, key_pem)`.

    Used by `scripts/init-ca.sh`. Lives here rather than in the script so the CA the tests
    exercise is built by the same code the operator runs — a script with its own generation logic
    is a second implementation of the thing under test, which is pattern F.

    P-256 rather than RSA: the device keys are P-256 (§3.1), and a mixed-algorithm chain buys
    nothing while adding a second key type to every code path. The key is returned **unencrypted**
    because it is written to `.env`, which no passphrase would protect — a passphrase stored beside
    the key it protects is theatre. The honest control is that `.env` is git-ignored and the
    pre-push scan refuses key material (§14.2, OQ-31).
    """
    now = (clock or (lambda: datetime.now(UTC)))().astimezone(UTC)
    key = ec.generate_private_key(ec.SECP256R1())
    subject = x509.Name(
        [
            x509.NameAttribute(NameOID.ORGANIZATION_NAME, CA_ORGANISATION),
            x509.NameAttribute(NameOID.COMMON_NAME, CA_COMMON_NAME),
        ]
    )
    certificate = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(subject)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - timedelta(minutes=1))
        .not_valid_after(now + timedelta(days=_CA_TTL_DAYS))
        # `path_length=0`: this CA may sign leaves and may not sign another CA. A development CA
        # that could mint intermediates is a development CA that can be turned into a PKI by
        # accident.
        .add_extension(x509.BasicConstraints(ca=True, path_length=0), critical=True)
        .add_extension(
            x509.KeyUsage(
                digital_signature=True,
                content_commitment=False,
                key_encipherment=False,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=True,
                crl_sign=False,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        .add_extension(x509.SubjectKeyIdentifier.from_public_key(key.public_key()), critical=False)
        .sign(key, hashes.SHA256())
    )
    return (
        certificate.public_bytes(serialization.Encoding.PEM),
        key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        ),
    )
