// SPDX-License-Identifier: Apache-2.0

package envelope

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// The cross-runtime fixture corpus (design §7.6, §10.4; Q-14; tasks.md leaf 7.4).
//
// `backend/src/governance/envelope.py` and this package are two implementations of one
// byte-level contract. §7.6 makes them read the SAME files, so a divergence fails both suites
// instead of surfacing in production as a signature error nobody can explain.
//
// The corpus is generated by `scripts/gen-envelope-fixtures.py` from the Python
// implementation and verified here INDEPENDENTLY. That asymmetry is what makes it a two-way
// lock: break Python and Python fails against the committed bytes; break Go and this file
// fails against them; regenerate after breaking Python and this file fails, which is the case
// the whole arrangement exists to catch.

const corpusDir = "../../testdata/envelopes"

// corpusFloor and invalidCorpusFloor are committed integers that may only be raised.
//
// The same mechanism as §0.4.2's INVENTORY_FLOOR, for the same reason: a glob that matched
// nothing would make every assertion below pass over an empty slice, and a suite that proves
// nothing looks exactly like a suite that proves everything.
const (
	corpusFloor        = 8
	invalidCorpusFloor = 6
)

type corpusFixture struct {
	Fixture            string          `json:"fixture"`
	Name               string          `json:"name"`
	Why                string          `json:"why"`
	KeyUTF8            string          `json:"key_utf8"`
	DomainPrefix       string          `json:"domain_prefix"`
	Envelope           json.RawMessage `json:"envelope"`
	CanonicalHex       string          `json:"canonical_hex"`
	CanonicalUTF8      string          `json:"canonical_utf8"`
	SigningInputSHA256 string          `json:"signing_input_sha256"`
	Signature          string          `json:"signature"`
}

type invalidFixture struct {
	Fixture        string          `json:"fixture"`
	Name           string          `json:"name"`
	Why            string          `json:"why"`
	KeyUTF8        string          `json:"key_utf8"`
	DomainPrefix   string          `json:"domain_prefix"`
	Reject         string          `json:"reject"`
	Envelope       json.RawMessage `json:"envelope"`
	ValidSignature string          `json:"valid_signature"`
}

func loadCorpus(t *testing.T) []corpusFixture {
	t.Helper()
	paths, err := filepath.Glob(filepath.Join(corpusDir, "*.json"))
	if err != nil {
		t.Fatalf("globbing the corpus: %v", err)
	}
	if len(paths) < corpusFloor {
		t.Fatalf("corpus has %d fixtures, the committed floor is %d; a glob that matched nothing "+
			"would make every assertion in this file vacuous", len(paths), corpusFloor)
	}
	out := make([]corpusFixture, 0, len(paths))
	for _, path := range paths {
		raw, readErr := os.ReadFile(path) //nolint:gosec // a committed test fixture path
		if readErr != nil {
			t.Fatalf("reading %s: %v", path, readErr)
		}
		var fixture corpusFixture
		if err := json.Unmarshal(raw, &fixture); err != nil {
			t.Fatalf("parsing %s: %v", path, err)
		}
		if fixture.Fixture != "forgeops-envelope-fixture-v1" {
			t.Fatalf("%s declares fixture kind %q; the corpus and the reader must agree on a version",
				path, fixture.Fixture)
		}
		if fixture.Why == "" {
			t.Fatalf("%s has no `why`; a fixture whose purpose is not written down becomes one "+
				"nobody dares change and nobody can explain", path)
		}
		out = append(out, fixture)
	}
	return out
}

func loadInvalidCorpus(t *testing.T) []invalidFixture {
	t.Helper()
	paths, err := filepath.Glob(filepath.Join(corpusDir, "invalid", "*.json"))
	if err != nil {
		t.Fatalf("globbing the invalid corpus: %v", err)
	}
	if len(paths) < invalidCorpusFloor {
		t.Fatalf("invalid corpus has %d fixtures, the committed floor is %d", len(paths), invalidCorpusFloor)
	}
	out := make([]invalidFixture, 0, len(paths))
	for _, path := range paths {
		raw, readErr := os.ReadFile(path) //nolint:gosec // a committed test fixture path
		if readErr != nil {
			t.Fatalf("reading %s: %v", path, readErr)
		}
		var fixture invalidFixture
		if err := json.Unmarshal(raw, &fixture); err != nil {
			t.Fatalf("parsing %s: %v", path, err)
		}
		if fixture.Fixture != "forgeops-envelope-invalid-fixture-v1" {
			t.Fatalf("%s declares fixture kind %q", path, fixture.Fixture)
		}
		out = append(out, fixture)
	}
	return out
}

// envelopeFrom decodes a fixture's `envelope` member the way Verify's parser does.
func envelopeFrom(t *testing.T, raw json.RawMessage) Envelope {
	t.Helper()
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	decoder.UseNumber()
	var env Envelope
	if err := decoder.Decode(&env); err != nil {
		t.Fatalf("decoding the fixture envelope: %v", err)
	}
	return env
}

func TestCorpus_CanonicalBytesMatchTheCommittedHex(t *testing.T) {
	for _, fixture := range loadCorpus(t) {
		t.Run(fixture.Name, func(t *testing.T) {
			env := envelopeFrom(t, fixture.Envelope)
			canonical, err := CanonicalBytes(env)
			if err != nil {
				t.Fatalf("CanonicalBytes: %v", err)
			}
			want, err := hex.DecodeString(fixture.CanonicalHex)
			if err != nil {
				t.Fatalf("canonical_hex is not hex: %v", err)
			}
			if !bytes.Equal(canonical, want) {
				t.Fatalf("canonical bytes differ from the Python side.\n go: %q\n py: %q",
					string(canonical), string(want))
			}
		})
	}
}

// TestCorpus_CanonicalUTF8AgreesWithTheHex closes a hand-edit hole in the corpus itself.
//
// The fixtures carry the canonical bytes twice — as hex, which is authoritative and immune to
// an editor's line-ending or encoding habits, and as UTF-8 text, which is what a reviewer
// actually reads. Editing one without the other would leave a fixture that looks right and
// tests something else.
func TestCorpus_CanonicalUTF8AgreesWithTheHex(t *testing.T) {
	for _, fixture := range loadCorpus(t) {
		t.Run(fixture.Name, func(t *testing.T) {
			want, err := hex.DecodeString(fixture.CanonicalHex)
			if err != nil {
				t.Fatalf("canonical_hex is not hex: %v", err)
			}
			if fixture.CanonicalUTF8 != string(want) {
				t.Fatalf("canonical_utf8 and canonical_hex disagree:\n utf8: %q\n hex:  %q",
					fixture.CanonicalUTF8, string(want))
			}
		})
	}
}

func TestCorpus_SigningInputDigestMatches(t *testing.T) {
	for _, fixture := range loadCorpus(t) {
		t.Run(fixture.Name, func(t *testing.T) {
			env := envelopeFrom(t, fixture.Envelope)
			input, err := SigningInput(fixture.DomainPrefix, env)
			if err != nil {
				t.Fatalf("SigningInput: %v", err)
			}
			sum := sha256.Sum256(input)
			if got := hex.EncodeToString(sum[:]); got != fixture.SigningInputSHA256 {
				t.Fatalf("signing-input digest mismatch\n go: %s\n py: %s", got, fixture.SigningInputSHA256)
			}
			// The prefix and separator must be the leading bytes, not merely present.
			wantPrefix := append([]byte(fixture.DomainPrefix), 0x00)
			if !bytes.HasPrefix(input, wantPrefix) {
				t.Fatalf("signing input does not start with %q||0x00", fixture.DomainPrefix)
			}
		})
	}
}

func TestCorpus_SignatureMatchesUnderTheSyntheticKey(t *testing.T) {
	for _, fixture := range loadCorpus(t) {
		t.Run(fixture.Name, func(t *testing.T) {
			if !strings.HasPrefix(fixture.KeyUTF8, "test-only-not-a-real-secret") {
				t.Fatalf("fixture key %q is not self-labelling as synthetic; "+
					".antigravity/steering/secret-safety.md requires that it is", fixture.KeyUTF8)
			}
			env := envelopeFrom(t, fixture.Envelope)
			signature, err := Sign(fixture.DomainPrefix, env, []byte(fixture.KeyUTF8))
			if err != nil {
				t.Fatalf("Sign: %v", err)
			}
			if signature != fixture.Signature {
				t.Fatalf("signature mismatch\n go: %s\n py: %s", signature, fixture.Signature)
			}
		})
	}
}

// TestCorpus_TheOtherDomainPrefixNeverProducesTheSameSignature is Q-14's negative control made
// executable: "remove the domain-separation prefix on one side only" must break something.
func TestCorpus_TheOtherDomainPrefixNeverProducesTheSameSignature(t *testing.T) {
	for _, fixture := range loadCorpus(t) {
		t.Run(fixture.Name, func(t *testing.T) {
			other := ApprovalDomainPrefix
			if fixture.DomainPrefix == ApprovalDomainPrefix {
				other = DomainPrefix
			}
			env := envelopeFrom(t, fixture.Envelope)
			wrong, err := Sign(other, env, []byte(fixture.KeyUTF8))
			if err != nil {
				t.Fatalf("Sign under %s: %v", other, err)
			}
			if wrong == fixture.Signature {
				t.Fatalf("signature under %q equals the signature under %q, so domain separation "+
					"is not doing anything", other, fixture.DomainPrefix)
			}
			// Canonical bytes, by contrast, MUST be identical — the prefix separates the
			// signing input, not the document.
			canonicalWithOther, err := CanonicalBytes(env)
			if err != nil {
				t.Fatalf("CanonicalBytes: %v", err)
			}
			if hex.EncodeToString(canonicalWithOther) != fixture.CanonicalHex {
				t.Fatal("the prefix changed the canonical bytes; it must change only the signing input")
			}
		})
	}
}

// TestCorpus_ContainsNoFloatAnywhere asserts §7.6's precondition over the corpus itself.
//
// Asserted over the raw fixture JSON rather than over the parsed Envelope, because `args`
// survives as json.RawMessage and a float inside it would otherwise never be looked at here.
func TestCorpus_ContainsNoFloatAnywhere(t *testing.T) {
	for _, fixture := range loadCorpus(t) {
		t.Run(fixture.Name, func(t *testing.T) {
			decoder := json.NewDecoder(bytes.NewReader(fixture.Envelope))
			decoder.UseNumber()
			var value any
			if err := decoder.Decode(&value); err != nil {
				t.Fatalf("decoding the fixture envelope: %v", err)
			}
			if err := walkNoFloat(value, "envelope"); err != nil {
				t.Fatalf("the corpus carries a value §7.6 forbids: %v", err)
			}
		})
	}
}

// TestCorpus_VerifyAcceptsTheCommittedSignature drives the whole six-check path, not just the
// canonicaliser, so the corpus proves an END-TO-END agreement rather than a shared subroutine.
//
// One fixture is not verifiable by construction, and it is asserted rather than skipped —
// `scripts/check-no-skips.py --go` treats every Go test as mandatory, and §0.4.4 is explicit
// that a skip inside a green run is indistinguishable from coverage. So instead of stepping
// over it, `TestCorpus_TheUnverifiableFixturesAreRejectedForTheirStatedReason` below asserts
// exactly why it is rejected.
//
// It was two until D-83. `08-non-mutating-no-approval` was excluded because `parse` required a
// non-empty `approval_id` for every operation, which refused §7.7's read-only half; that check
// now lives in the dispatcher, where "mutating" is knowable, so the fixture verifies like any
// other and this test's coverage grew by one without a new fixture being written.
func TestCorpus_VerifyAcceptsTheCommittedSignature(t *testing.T) {
	verified := 0
	for _, fixture := range loadCorpus(t) {
		env := envelopeFrom(t, fixture.Envelope)
		if !verifiable(fixture, env) {
			continue
		}
		t.Run(fixture.Name, func(t *testing.T) {
			wire := wireBytes(t, fixture)
			verifier, guard := verifierFor(t, fixture, env)
			_ = guard
			result, err := verifier.Verify(context.Background(), wire)
			if err != nil {
				t.Fatalf("Verify rejected a correctly signed fixture: %v", err)
			}
			if result.Seq() != env.Seq {
				t.Fatalf("Verified seq %d, fixture seq %d", result.Seq(), env.Seq)
			}
		})
		verified++
	}
	if verified == 0 {
		t.Fatal("no fixture reached Verify; every assertion in this test would then be vacuous")
	}
	if verified == len(loadCorpus(t)) {
		t.Fatal("every fixture reached Verify, so the corpus no longer covers the documented " +
			"non-verifiable shape; see TestCorpus_TheUnverifiableFixturesAreRejectedForTheirStatedReason")
	}
}

// verifiable reports whether Verify can accept a fixture at all.
//
// One shape cannot, and it is in the corpus on purpose: an envelope signed under
// `forgeops-approval-v1`. Verify checks the command prefix by construction, so an approval
// response is not a command and must not verify as one.
//
// A read-only operation with an empty `approval_id` used to be the second such shape. D-83
// removed it: the requirement is operation-dependent, so it moved to the dispatcher, and the
// fixture is now an ordinary verifiable one.
func verifiable(fixture corpusFixture, _ Envelope) bool {
	return fixture.DomainPrefix == DomainPrefix
}

func verifierFor(t *testing.T, fixture corpusFixture, env Envelope) (*Verifier, *MemoryReplayGuard) {
	t.Helper()
	keys := NewStaticKeySource()
	keys.Set(env.DeviceID, []byte(fixture.KeyUTF8))
	guard, err := NewMemoryReplayGuard(300*time.Second, 128)
	if err != nil {
		t.Fatalf("NewMemoryReplayGuard: %v", err)
	}
	// A fresh verifier per fixture: seq is a per-device high-water mark and the corpus
	// deliberately includes a seq at RFC 8785's integer boundary, which would lock out every
	// later fixture sharing the device id.
	verifier, err := NewVerifier(keys, guard, NewStaticBundleDigest(env.PolicyContext.BundleDigest),
		WithClock(func() time.Time { return time.Unix(env.NotAfter-60, 0) }))
	if err != nil {
		t.Fatalf("NewVerifier: %v", err)
	}
	return verifier, guard
}

// TestCorpus_TheUnverifiableFixturesAreRejectedForTheirStatedReason turns the exclusion
// above into an assertion, so nothing in this file is stepped over silently.
func TestCorpus_TheUnverifiableFixturesAreRejectedForTheirStatedReason(t *testing.T) {
	seen := 0
	for _, fixture := range loadCorpus(t) {
		env := envelopeFrom(t, fixture.Envelope)
		if verifiable(fixture, env) {
			continue
		}
		t.Run(fixture.Name, func(t *testing.T) {
			seen++
			wire := wireBytes(t, fixture)
			verifier, _ := verifierFor(t, fixture, env)
			_, err := verifier.Verify(context.Background(), wire)
			if err == nil {
				t.Fatal("Verify accepted an envelope it cannot legitimately accept")
			}
			switch {
			case fixture.DomainPrefix != DomainPrefix:
				// The signature was computed over `forgeops-approval-v1|| 0x00 || …`, so the
				// command-prefix MAC cannot match. This is domain separation observed from the
				// verifier's side rather than from the signer's.
				if !errors.Is(err, ErrSignature) {
					t.Fatalf("expected a signature failure for an approval-prefixed envelope, got %v", err)
				}
			default:
				t.Fatalf("fixture %q is not verifiable for a reason this test does not know about",
					fixture.Name)
			}
		})
	}
	if seen == 0 {
		t.Fatal("the corpus no longer contains the documented non-verifiable shape, so this " +
			"test proves nothing; add one back or delete this test deliberately")
	}
}

// wireBytes rebuilds the on-the-wire JSON: the fixture's envelope plus its signature.
//
// The corpus stores the envelope WITHOUT `signature`, because that is what is canonicalised,
// and there is no code path that removes the member — absence by construction cannot be
// forgotten the way a removal step can.
func wireBytes(t *testing.T, fixture corpusFixture) []byte {
	t.Helper()
	var members map[string]json.RawMessage
	if err := json.Unmarshal(fixture.Envelope, &members); err != nil {
		t.Fatalf("unmarshalling the fixture envelope: %v", err)
	}
	if _, present := members["signature"]; present {
		t.Fatal("the corpus stores the envelope without `signature`; found one")
	}
	encoded, err := json.Marshal(fixture.Signature)
	if err != nil {
		t.Fatalf("marshalling the signature: %v", err)
	}
	members["signature"] = encoded
	wire, err := json.Marshal(members)
	if err != nil {
		t.Fatalf("marshalling the wire envelope: %v", err)
	}
	return wire
}

// TestInvalidCorpus_EveryFixtureIsRefusedForItsStatedReason is the corpus's other half.
//
// A corpus of documents that must be accepted proves the happy path agrees. It says nothing
// about whether the two runtimes REFUSE the same documents — and a pair that disagrees about
// which documents exist is worse than a pair that disagrees about bytes, because one side
// reports "malformed" and the other "signature invalid" for the same input.
//
// `reject` is a token rather than a message, so neither suite is coupled to the other's prose.
func TestInvalidCorpus_EveryFixtureIsRefusedForItsStatedReason(t *testing.T) {
	for _, fixture := range loadInvalidCorpus(t) {
		t.Run(fixture.Name, func(t *testing.T) {
			err := refuse(fixture)
			if err == nil {
				t.Fatalf("fixture %q was accepted; it must be refused because: %s", fixture.Name, fixture.Why)
			}
			want, known := map[string]error{
				"float":                   ErrFloatValue,
				"integer-domain":          ErrIntegerDomain,
				"unknown-member":          ErrSchema,
				"args-not-object":         ErrSchema,
				"seq-not-integer":         ErrSchema,
				"signature-non-canonical": ErrSchema,
			}[fixture.Reject]
			if !known {
				t.Fatalf("fixture %q declares the unknown reject token %q; add it to both suites "+
					"or the fixture proves nothing", fixture.Name, fixture.Reject)
			}
			if !errors.Is(err, want) {
				t.Fatalf("fixture %q was refused with %v, expected %v", fixture.Name, err, want)
			}
		})
	}
}

// refuse runs the step the fixture's reject token names, and returns the error it produced.
func refuse(fixture invalidFixture) error {
	if fixture.Reject == "signature-non-canonical" {
		var members map[string]json.RawMessage
		if err := json.Unmarshal(fixture.Envelope, &members); err != nil {
			return fmt.Errorf("%w: %v", ErrSchema, err)
		}
		var signature string
		if err := json.Unmarshal(members["signature"], &signature); err != nil {
			return fmt.Errorf("%w: %v", ErrSchema, err)
		}
		if signature == fixture.ValidSignature {
			return fmt.Errorf("%w: the fixture's signature equals the canonical spelling, so it "+
				"tests nothing", ErrSchema)
		}
		_, err := DecodeSignature(signature)
		return err
	}

	decoder := json.NewDecoder(bytes.NewReader(fixture.Envelope))
	decoder.DisallowUnknownFields()
	decoder.UseNumber()
	var env Envelope
	if err := decoder.Decode(&env); err != nil {
		return fmt.Errorf("%w: %v", ErrSchema, err)
	}
	_, err := CanonicalBytes(env)
	return err
}
